export const INTEGRATION_API_SCOPES = [
  'integration:documents:nfe:emit',
  'integration:documents:nfe:consult',
  'integration:documents:nfe:events:emit',
  'integration:documents:nfe:events:consult',
  'integration:documents:nfe:items:emit',
  'integration:documents:nfe:items:consult',
  'integration:documents:nfe:timeline:emit',
  'integration:documents:nfe:timeline:consult',
  'integration:documents:nfe:attachments:emit',
  'integration:documents:nfe:attachments:consult',
  'integration:documents:nfe:inbound-process:emit',
  'integration:documents:nfe:inbound-process:consult',
  'integration:documents:nfe:sap-documents:emit',
  'integration:documents:nfe:sap-documents:consult',
  'integration:documents:nfse:emit',
  'integration:documents:nfse:consult',
  'integration:documents:nfse:events:emit',
  'integration:documents:nfse:events:consult',
  'integration:documents:nfse:items:emit',
  'integration:documents:nfse:items:consult',
  'integration:documents:nfse:timeline:emit',
  'integration:documents:nfse:timeline:consult',
  'integration:documents:nfse:attachments:emit',
  'integration:documents:nfse:attachments:consult',
  'integration:documents:nfse:inbound-process:emit',
  'integration:documents:nfse:inbound-process:consult',
  'integration:documents:nfse:sap-documents:emit',
  'integration:documents:nfse:sap-documents:consult',
  'integration:companies:number-ranges:nfe:emit',
  'integration:companies:number-ranges:nfe:consult',
  'integration:companies:number-ranges:nfe:events:emit',
  'integration:companies:number-ranges:nfe:events:consult',
  'integration:companies:number-ranges:nfse:emit',
  'integration:companies:number-ranges:nfse:consult',
  'integration:companies:number-ranges:nfse:events:emit',
  'integration:companies:number-ranges:nfse:events:consult',
] as const;

export const INTEGRATION_SCOPE_OPTIONS = INTEGRATION_API_SCOPES.map((scope) => ({
  value: scope,
  label: scope,
}));

export const WEBHOOK_EVENT_TYPES = [
  'nfe.document.created',
  'nfe.document.sent_to_sefaz',
  'nfe.document.authorized',
  'nfe.document.rejected',
  'nfe.document.cancelled',
  'nfe.document.updated',
  'nfe.document_event.created',
  'nfe.document_event.accepted',
  'nfe.document_event.rejected',
  'nfe.item.created',
  'nfe.item.pedido_validated',
  'nfe.timeline.created',
  'nfe.attachment.created',
  'nfe.inbound.status_changed',
  'nfe.sap_document.created',
  'nfe.number_range.created',
  'nfe.number_range.inutilized',
  'nfe.number_range_event.created',
  'nfse.document.created',
  'nfse.document.sent_to_prefeitura',
  'nfse.document.authorized',
  'nfse.document.rejected',
  'nfse.document.cancelled',
  'nfse.document.updated',
  'nfse.document_event.created',
  'nfse.document_event.accepted',
  'nfse.document_event.rejected',
  'nfse.item.created',
  'nfse.item.pedido_validated',
  'nfse.timeline.created',
  'nfse.attachment.created',
  'nfse.inbound.status_changed',
  'nfse.sap_document.created',
  'nfse.number_range.created',
  'nfse.number_range.inutilized',
  'nfse.number_range_event.created',
] as const;

export const WEBHOOK_EVENT_TYPE_OPTIONS = WEBHOOK_EVENT_TYPES.map((eventType) => ({
  value: eventType,
  label: eventType,
}));

export const INTEGRATION_ROLE_PERMISSIONS = [
  'integration:tokens:manage',
  'integration:webhooks:manage',
] as const;

export const INTEGRATION_ROLE_PERMISSION_OPTIONS = INTEGRATION_ROLE_PERMISSIONS.map(
  (permission) => ({
    value: permission,
    label: permission,
  }),
);
