export const FISCAL_NFE_EVENT_TYPES = [
  'authorization',
  'cancellation',
  'cancellation_denied',
  'correction_letter',
  'manifestation_confirmation',
  'manifestation_unknown',
  'manifestation_not_performed',
  'manifestation_awareness',
  'epec',
  'protocol_query',
  'status_query',
  'distribution_dfe',
  'xml_import',
  'xml_export',
  'system_status_change',
  'webhook_callback',
  'sap_callback',
  'manual_note',
  'inbound_status_change',
  'pedido_validation',
  'sap_delivery_create',
  'sap_migo',
  'sap_miro',
  'inbound_rejection',
  'portaria_confirmation',
] as const;

export type FiscalNfeEventType = (typeof FISCAL_NFE_EVENT_TYPES)[number];
